tcp_server:
  host: "127.0.0.1"
  port: 50000

web_server:
  host: "127.0.0.1"
  port: 8001

database:
  path: ".data/server"
  name: "server.db"
  cleanup_interval: 3600  # seconds
  retention_days: 7 